import './style.css';
const seed=[
{id:'d1',name:'Camisa branca',category:'Parte de cima',color:'Branco',style:'Clássico',image:'https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=600&q=80'},
{id:'d2',name:'Calça bege',category:'Parte de baixo',color:'Bege',style:'Minimalista',image:'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=600&q=80'},
{id:'d3',name:'Tênis branco',category:'Calçado',color:'Branco',style:'Casual',image:'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=80'}];
const load=(k,d)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):d}catch{return d}};
const state={page:'home',items:load('veste_items',seed),name:load('veste_name','Samuel'),style:load('veste_style','Minimalista'),filter:'Todas',query:'',modal:false,result:null};
const app=document.querySelector('#app');
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const save=()=>{localStorage.setItem('veste_items',JSON.stringify(state.items));localStorage.setItem('veste_name',JSON.stringify(state.name));localStorage.setItem('veste_style',JSON.stringify(state.style))};
function toast(text){document.body.insertAdjacentHTML('beforeend',`<div class="toast">✓ ${esc(text)}</div>`);setTimeout(()=>document.querySelector('.toast')?.remove(),2200)}
const feature=(i,t,d,g)=>`<button class="feature" data-go="${g}"><span class="ico">${i}</span><div><h3>${t}</h3><p>${d}</p></div><b>›</b></button>`;
function home(){const combos=Math.floor(state.items.length*(state.items.length-1)/2);return `<section class="page"><span class="eyebrow">SEU CLOSET INTELIGENTE</span><h1>Bom dia, ${esc(state.name)}.</h1><p class="lead">Menos tempo pensando. Mais tempo vivendo.</p><div class="hero"><span class="pill">☼ Look do dia</span><h2>Seu armário ainda tem muito para mostrar.</h2><p>Crie novas combinações usando apenas o que você já possui.</p><div class="buttons"><button class="btn primary" data-go="stylist">✦ Montar look</button><button class="btn ghost" data-add>＋ Adicionar peça</button></div><div class="look-stack">${state.items.slice(0,3).map((i,n)=>`<img src="${i.image}" style="transform:rotate(${(n-1)*7}deg) translateX(${(n-1)*12}px)">`).join('')}</div></div><div class="stats"><div><strong>${state.items.length}</strong><span>peças salvas</span></div><div><strong>${combos}</strong><span>combinações</span></div><div><strong>∞</strong><span>organização</span></div></div><span class="eyebrow">EXPLORE</span><h2>Tudo que seu armário pode fazer</h2><div class="features">${feature('✦','Estilista com IA','Sugestões para clima e ocasião','stylist')}${feature('👕','Armário digital','Organize todas as peças','closet')}${feature('▣','Planejador','Monte sua semana','planner')}${feature('✈','Mala inteligente','Viaje com menos peças','trip')}</div></section>`}
function closet(){const cats=['Todas',...new Set(state.items.map(i=>i.category))];const items=state.items.filter(i=>(state.filter==='Todas'||i.category===state.filter)&&(`${i.name} ${i.color}`.toLowerCase().includes(state.query.toLowerCase())));return `<section class="page"><div class="title-row"><div><span class="eyebrow">ARMÁRIO DIGITAL</span><h1>Meu closet</h1></div><button class="circle" data-add>＋</button></div><div class="search">⌕ <input id="search" value="${esc(state.query)}" placeholder="Buscar peça ou cor"></div><div class="chips">${cats.map(c=>`<button data-filter="${esc(c)}" class="${state.filter===c?'active':''}">${esc(c)}</button>`).join('')}</div><p class="lead" style="font-size:13px">${items.length} peças</p><div class="grid">${items.map(i=>`<article class="item"><img src="${i.image}"><h3>${esc(i.name)}</h3><p>${esc(i.category)} · ${esc(i.color)}</p><button class="btn ghost full" data-delete="${i.id}" style="padding:9px">Remover</button></article>`).join('')}</div>${!items.length?'<div class="empty">Nenhuma peça encontrada.</div>':''}</section>`}
function stylist(){return `<section class="page"><span class="eyebrow">SEU ESTILISTA COM IA</span><h1>O que você vai fazer?</h1><p class="lead">Receba um look usando seu próprio closet.</p><div class="form"><label>Ocasião<select id="occasion"><option>Dia a dia</option><option>Trabalho</option><option selected>Jantar</option><option>Encontro</option><option>Festa</option><option>Viagem</option></select></label><label>Clima<select id="weather"><option>Quente</option><option selected>Ameno</option><option>Frio</option><option>Chuvoso</option></select></label><label>Detalhes<textarea id="note" placeholder="Ex.: restaurante casual, não gosto de salto..."></textarea></label><button class="btn primary full" id="generate">✦ Criar meu look</button></div>${state.result?resultHtml():''}</section>`}
function resultHtml(){const picked=state.result.itemNames.map(n=>state.items.find(i=>i.name===n)).filter(Boolean);return `<div class="result"><span class="eyebrow">RECOMENDAÇÃO</span><h2>${esc(state.result.title)}</h2><div class="result-images">${picked.map(i=>`<img src="${i.image}">`).join('')}</div><p>${esc(state.result.reason)}</p><ul>${(state.result.tips||[]).map(t=>`<li>✓ ${esc(t)}</li>`).join('')}</ul></div>`}
function planner(){const days=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'];return `<section class="page"><span class="eyebrow">PLANEJADOR DE LOOKS</span><h1>Sua semana organizada.</h1><p class="lead">Veja combinações rápidas para cada dia.</p>${days.map((d,idx)=>`<article class="day"><div><b>${d}</b><div style="font-size:24px;font-weight:800">${14+idx}</div></div><div style="display:flex;gap:5px">${state.items.slice(idx%Math.max(1,state.items.length),idx%Math.max(1,state.items.length)+2).map(i=>`<img src="${i.image}">`).join('')||'Sem look'}</div><button class="circle" style="width:36px;height:36px">＋</button></article>`).join('')}</section>`}
function trip(){return `<section class="page"><span class="eyebrow">MALA INTELIGENTE</span><h1>Viaje leve.</h1><p class="lead">Planeje peças versáteis.</p><div class="form"><label>Destino<input placeholder="Ex.: Rio de Janeiro"></label><label>Dias<input type="number" value="4" min="1"></label></div><div class="grid">${state.items.slice(0,6).map(i=>`<article class="item"><img src="${i.image}"><h3>${esc(i.name)}</h3><p>${esc(i.color)}</p></article>`).join('')}</div></section>`}
function profile(){return `<section class="page"><span class="eyebrow">SEU PERFIL</span><h1>Seu estilo, suas regras.</h1><div class="hero" style="min-height:auto"><h2 style="max-width:100%;margin:0">${esc(state.name)}</h2><p>Acesso vitalício · Plano MVP</p></div><div class="form"><label>Seu nome<input id="name" value="${esc(state.name)}"></label><label>Estilo principal<select id="style">${['Casual','Minimalista','Clássico','Old Money','Romântico','Streetwear'].map(x=>`<option ${x===state.style?'selected':''}>${x}</option>`).join('')}</select></label><button class="btn primary full" id="saveProfile">Salvar perfil</button></div><div class="notice"><b>Seus dados ficam neste aparelho.</b><p>Não limpe os dados do site para não perder seu closet nesta versão.</p></div></section>`}
function modal(){return `<div class="modal"><div class="sheet"><div class="sheet-head"><div><span class="eyebrow">NOVA PEÇA</span><h2>Adicionar ao closet</h2></div><button class="circle" id="close">×</button></div><label class="upload" id="upload"><div id="uploadText">📷<br><b>Fotografe ou envie a roupa</b><br><small>Use boa iluminação</small></div><img id="preview" class="hidden"><input id="file" type="file" accept="image/*"></label><button class="btn ghost full" id="analyze" style="margin-top:10px">✦ Analisar com IA</button><div class="form"><label>Nome<input id="itemName" placeholder="Ex.: Camisa branca"></label><label>Categoria<select id="category"><option>Parte de cima</option><option>Parte de baixo</option><option>Vestido</option><option>Calçado</option><option>Roupa externa</option><option>Acessório</option></select></label><label>Cor<input id="color" placeholder="Ex.: Bege"></label><label>Estilo<select id="itemStyle"><option>Casual</option><option>Minimalista</option><option>Clássico</option><option>Old Money</option><option>Romântico</option><option>Streetwear</option></select></label><button class="btn primary full" id="saveItem">Salvar peça</button></div></div></div>`}
function shell(content){return `<header class="topbar"><div class="brand">Veste<span>.AI</span></div><button class="avatar" data-go="profile">${esc(state.name[0]||'V')}</button></header><main>${content}</main><nav class="nav">${[['home','⌂','Hoje'],['closet','👕','Closet'],['stylist','✦','Estilista'],['planner','▣','Planejar'],['profile','○','Perfil']].map(x=>`<button data-go="${x[0]}" class="${state.page===x[0]?'active':''}"><span style="font-size:20px">${x[1]}</span>${x[2]}</button>`).join('')}</nav>${state.modal?modal():''}`}
function render(){const views={home,closet,stylist,planner,trip,profile};app.innerHTML=shell((views[state.page]||home)());bind()}
function bind(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.page=b.dataset.go;render();window.scrollTo(0,0)});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{state.modal=true;render()});document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{state.items=state.items.filter(i=>i.id!==b.dataset.delete);save();render();toast('Peça removida')});document.querySelector('#search')?.addEventListener('input',e=>{state.query=e.target.value;render();setTimeout(()=>document.querySelector('#search')?.focus(),0)});document.querySelector('#close')?.addEventListener('click',()=>{state.modal=false;render()});const file=document.querySelector('#file');document.querySelector('#upload')?.addEventListener('click',()=>file?.click());file?.addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const data=await compress(f);const p=document.querySelector('#preview');p.src=data;p.classList.remove('hidden');p.dataset.data=data;document.querySelector('#uploadText')?.classList.add('hidden')});document.querySelector('#analyze')?.addEventListener('click',analyze);document.querySelector('#saveItem')?.addEventListener('click',saveItem);document.querySelector('#generate')?.addEventListener('click',generate);document.querySelector('#saveProfile')?.addEventListener('click',()=>{state.name=document.querySelector('#name').value||'Usuário';state.style=document.querySelector('#style').value;save();render();toast('Perfil salvo')})}
async function analyze(){const p=document.querySelector('#preview');if(!p?.dataset.data)return toast('Envie uma foto primeiro');const b=document.querySelector('#analyze');b.textContent='Analisando...';try{const r=await fetch('/.netlify/functions/analyze-clothing',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({image:p.dataset.data})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Erro');document.querySelector('#itemName').value=j.name||'';document.querySelector('#category').value=j.category||'Parte de cima';document.querySelector('#color').value=j.color||'';document.querySelector('#itemStyle').value=(Array.isArray(j.style)?j.style[0]:j.style)||'Casual';toast('Peça analisada')}catch{toast('IA indisponível; preencha manualmente')}finally{b.textContent='✦ Analisar com IA'}}
function saveItem(){const p=document.querySelector('#preview');const name=document.querySelector('#itemName').value.trim();if(!p?.dataset.data||!name)return toast('Envie a foto e informe o nome');state.items.unshift({id:String(Date.now()),name,category:document.querySelector('#category').value,color:document.querySelector('#color').value||'Não informada',style:document.querySelector('#itemStyle').value,image:p.dataset.data});state.modal=false;save();render();toast('Peça adicionada')}
async function generate(){if(state.items.length<2)return toast('Adicione ao menos 2 peças');const btn=document.querySelector('#generate');btn.textContent='Montando...';const occasion=document.querySelector('#occasion').value,weather=document.querySelector('#weather').value,note=document.querySelector('#note').value;try{const r=await fetch('/.netlify/functions/style-advice',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({occasion,weather,note,items:state.items.map(({name,category,color,style})=>({name,category,color,style}))})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Erro');state.result=j}catch{const chosen=state.items.slice(0,3);state.result={title:`Look para ${occasion.toLowerCase()}`,reason:'Combinação equilibrada com peças versáteis do seu closet.',itemNames:chosen.map(i=>i.name),tips:['Use um ponto de destaque','Finalize com acessórios discretos']}}render()}
function compress(file){return new Promise((resolve,reject)=>{const img=new Image();const url=URL.createObjectURL(file);img.onload=()=>{const max=1000;const scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve(c.toDataURL('image/jpeg',.76))};img.onerror=reject;img.src=url})}
window.addEventListener('error',e=>{app.innerHTML=`<div style="padding:30px"><h2>Erro ao abrir o app</h2><p>${esc(e.message)}</p></div>`});
render();
